GET http://localhost:4000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQnJhbmRvbiIsImlhdCI6MTcyOTU5MzkyM30.2TirxvIliSiv_NlrRw3eh0XsiVLUwQAHZR-UtwOoMj8

###

POST http://localhost:3000/login
Content-Type: application/json

{
    "username" : "Brandon"
}